trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/'
    backendServiceAWS: 'aws-for-terraform'
    backendAWSBucketName: 'terraform-backend-state-in28minutes-123'
    backendAWSKey: 'kubernetes-dev.tfstate'
- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/'
    environmentServiceNameAWS: 'aws-for-terraform'

